### ISSUE TITLE
GitHub Community Leader Skills

### ISSUE THREAD

**Issue by AndreaGriffiths11** [githubpresente/CommunityLeaders#12]
| Nombre del Lider | Habilidades | Ubicación | Dispuesto a hablar en público: Si o No|
|--------------------------|-------------|-----------|-------------------------------|
| Dorian Higaldo           |             |           |                               |
| Kevin Villatoro          |             |           |                               |
| Oscar Barajas            |             |           |                               |
| Denny Perez              |             |           |                               |
| Vanessa Marely           |             |           |                               |
| Vicente Guzman           |             |           |                               |

**Comment by LucioMSP** [comment]
<html>
<body>


Nombre del Lider | Habilidades | Ubicación | Dispuesto a hablar en público: Si o No
-- | -- | -- | --
-- | -- | -- | --
-- | -- | -- | --
-- | -- | -- | --
-- | -- | -- | --
-- | -- | -- | --
Vicente Guzmán | GitHub - Alexa Skills - Azure - Xamarin - AWS - Power Platform | Ciudad de México, MX | Si



</body>
</html>

**Comment by vanessamarely** [comment]
| Nombre del Lider      | Habilidades | Ubicación   | Dispuesto a hablar en público: Si o No   |
|    :----:         |    :----:   |        :----:  | :----:  |
| Vanessa Marely      | Web (HTML, CSS, Javascript, Typescript, React/Next.js, Angular, ...) - Github - Soft Skills    | Medellin  | Si   |
